[package]
name = "shufflebuf"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/tstellanova/shufflebuf-rs"


[dependencies]
